# Generated by Django 4.1.1 on 2022-10-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_patient_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
