# Generated by Django 4.1.1 on 2022-10-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_patient_address_patient_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
