# Generated by Django 4.1.1 on 2022-10-13 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='provider',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='main_app.provider'),
            preserve_default=False,
        ),
    ]
