# Generated by Django 4.1.1 on 2022-10-13 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='main_app.provider'),
        ),
    ]
