# Generated by Django 4.1.1 on 2022-10-13 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='main_app.patient'),
        ),
    ]
